export const AUTH_FAILED_ALERT = 'authentication_failed'
export const SHOW_ALERT = 'show_alert'
export const FORGOT_PASSWORD_SUCCESS = 'forgot_password_success'
export const UPDATE_USER_INFO = 'update_user_info'
export const UPDATE_USER_ORDERS = 'update_user_orders'
export const UPDATE_USER_NETWORKING = 'update_user_networking'
export const CLEAR_ALERT = 'clear_alert'
